### ISSUE TITLE
The docker entry script does not delete existing pid files

### ISSUE THREAD

**Issue by micheasherman-minted** [Ticketmaster/techmaturity#10]
If the docker instance is restarted it does not clear the pid file so you have to manually rush to exec an rm of the pid file so it will start

**Comment by vigneshjb** [comment]
@micheasherman-minted : We have added `dumb-init` to take care of the docker start and SIGINT commands in Version 2.0.0. Please try out the new version and let us know how it worked out. Thank you.

**Comment by micheasherman-minted** [comment]
It seems to be working fine for me
