### ISSUE TITLE
Deleting Assets?

### ISSUE THREAD

**Issue by kenerwin88** [Ticketmaster/techmaturity#7]
Hi!  

I think this is absolutely awesome so far!  One quick issue, there doesn't appear to be any way of deleting assets?  I'd like to remove the example asset and start from scratch, but I don't think it's possible yet?  Love the work you're doing!

Ken

**Comment by seakitteh** [comment]
Hey Ken! Totally reasonable ask and we love to hear that you're enjoying Tech Maturity so far! Please continue to share feedback as you use it more... We'll take a look! Talk soon...

**Comment by vigneshjb** [comment]
Hello @kenerwin88, Thanks for the testing out tech maturity. We are glad that you enjoy it. I have added the remove asset button and pushed it on master. I'll release the docker image for the same soon enough. I'll post an update here once I get to it.

**Comment by kenerwin88** [comment]
Thank you so much!  It's such a great idea for a project, very helpful for gauging our progress!

**Comment by vigneshjb** [comment]
@kenerwin88 : I have released the new docker image and I have updated the Readme about the same. Please feel free to try it out !!

**Comment by kenerwin88** [comment]
awesome news! thank you so much!
